(function(){
    var modules={
        "panel-main-sdm-ii":    			{url:"$A/components/panel/panel-main.html",router:1},
        "panel-child-sdm-ii":    			{url:"$A/components/panel/panel-child.html"},
        
        "participant-data":   		{url:"$A/components/participant/participant-data.html",Table:"sdm-ii-participant",form_module:"participant-form",router:1,
                                            child_panel:"panel-child-sdm-ii",
                                            questionnaire_setup:"online-questionnaire-setup-sdm-ii",
                                            online_questionnaire:"online-questionnaire-app-sdm-ii",
                                            participant_id:{field1:"Subject_ID",field2:"Subject_Initials"}
                                        },
        "participant-form":   		{url:"$A/components/participant/participant-form.html",Table:"sdm-ii-participant"},

        "online-questionnaire-setup-sdm-ii": 	{url:"$A/modulesnline-questionnaire/components/modulesnline-questionnaire-setup.html",Table:"sdm-ii-participant"},
        "online-questionnaire-app-sdm-ii":    {url:"$A/modulesnline-questionnaire/index.html"},

        "notes":  		  	  			{url:"$A/modules/notes.html"},

        "sdm-ii-randomisation-table-data":		    {url:"$A/modules/randomisation-table-data.html",Table:"sdm-ii-randomisation-table",form_module:"sdm-ii-randomisation-table-form"},
        "sdm-ii-randomisation-table-form":		    {url:"$A/modules/randomisation-table-form.html",Table:"sdm-ii-randomisation-table"},
        "sdm-ii-concom-medication-data":            {url:"$A/modules/concom-medication-data.html",Table:"sdm-ii-concom-medication",form_module:"sdm-ii-concom-medication-form"},
        "sdm-ii-concom-medication-form":            {url:"$A/modules/concom-medication-form.html",Table:"sdm-ii-concom-medication"},
        "sdm-ii-adverse-event-data":                {url:"$A/modules/adverse-event-data.html",Table:"sdm-ii-adverse-event",form_module:"sdm-ii-adverse-event-form"},
        "sdm-ii-adverse-event-form":                {url:"$A/modules/adverse-event-form.html",Table:"sdm-ii-adverse-event"},

        "sdm-ii-s-date-data":		                {url:"$A/modules/date-data.html",Table:"sdm-ii-s-date",form_module:"sdm-ii-s-date-form"},
        "sdm-ii-s-date-form":		                {url:"$A/modules/date-form.html",Table:"sdm-ii-s-date"},
        "sdm-ii-s-screening-data":		                        {url:"$A/modules/screening-data.html",Table:"sdm-ii-s-screening",form_module:"sdm-ii-s-screening-form"},
        "sdm-ii-s-screening-form":		                {url:"$A/modules/screening-form.html",Table:"sdm-ii-s-screening"},

        "sdm-ii-b-patient-background-data":		            {url:"$A/modules/patient-background-data.html",Table:"sdm-ii-b-patient-background",form_module:"sdm-ii-b-patient-background-form"},
        "sdm-ii-b-patient-background-form":		            {url:"$A/modules/patient-background-form.html",Table:"sdm-ii-b-patient-background"},
        "sdm-ii-b-medical-history-data":		            {url:"$A/modules/medical-history-data.html",Table:"sdm-ii-b-medical-history",form_module:"sdm-ii-b-medical-history-form"},
        "sdm-ii-b-medical-history-form":		            {url:"$A/modules/medical-history-form.html",Table:"sdm-ii-b-medical-history"},
        "sdm-ii-b-medications-data":		            {url:"$A/modules/medications-data.html",Table:"sdm-ii-b-medications",form_module:"sdm-ii-b-medications-form"},
        "sdm-ii-b-medications-form":		            {url:"$A/modules/medications-form.html",Table:"sdm-ii-b-medications"},
        "sdm-ii-b-fina-data":		            {url:"$A/modules/finapres-data.html",Table:"sdm-ii-b-fina",form_module:"sdm-ii-b-fina-form"},
        "sdm-ii-b-fina-form":		            {url:"$A/modules/finapres-form.html",Table:"sdm-ii-b-fina"},
        "sdm-ii-b-nirs-data":		            {url:"$A/modules/nirs-data.html",Table:"sdm-ii-b-nirs",form_module:"sdm-ii-b-nirs-form"},
        "sdm-ii-b-nirs-form":		            {url:"$A/modules/nirs-form.html",Table:"sdm-ii-b-nirs"},

        "sdm-ii-b-pre-pvt-data":		            {url:"$A/modules/pvt-data.html",Table:"sdm-ii-b-pre-pvt",form_module:"sdm-ii-b-pre-pvt-form"},
        "sdm-ii-b-pre-pvt-form":		            {url:"$A/modules/pvt-form.html",Table:"sdm-ii-b-pre-pvt"},
        "sdm-ii-b-pre-word-pairs-set1-evening":	    {url:"$A/modules/word-pairs/set1-evening.html"},
        "sdm-ii-b-pre-word-pairs-set2-evening":	    {url:"$A/modules/word-pairs/set2-evening.html"},
        "sdm-ii-b-pre-declarative-memory-test-data":		            {url:"$A/modules/declarative-memory-test-data.html",Table:"sdm-ii-b-pre-declarative-memory-test",form_module:"sdm-ii-b-pre-declarative-memory-test-form"},
        "sdm-ii-b-pre-declarative-memory-test-form":		            {url:"$A/modules/declarative-memory-test-form.html",Table:"sdm-ii-b-pre-declarative-memory-test"},
        "sdm-ii-b-pre-procedural-memory-test-data":		            {url:"$A/modules/procedural-memory-test-data.html",Table:"sdm-ii-b-pre-procedural-memory-test",form_module:"sdm-ii-b-pre-procedural-memory-test-form"},
        "sdm-ii-b-pre-procedural-memory-test-form":		            {url:"$A/modules/procedural-memory-test-form.html",Table:"sdm-ii-b-pre-procedural-memory-test"},

        "sdm-ii-b-pre-kss-data":		            {url:"$A/modules/kss-data.html",Table:"sdm-ii-b-pre-kss",form_module:"sdm-ii-b-pre-kss-form"},
        "sdm-ii-b-pre-kss-form":		            {url:"$A/modules/kss-form.html",Table:"sdm-ii-b-pre-kss"},

        "sdm-ii-b-pwa-data":		            {url:"$A/modules/pwa-data.html",Table:"sdm-ii-b-pwa",form_module:"sdm-ii-b-pwa-form"},
        "sdm-ii-b-pwa-form":		            {url:"$A/modules/pwa-form.html",Table:"sdm-ii-b-pwa"},
        "sdm-ii-b-psg300-data":		            {url:"$A/modules/psg300-data.html",Table:"sdm-ii-b-psg300",form_module:"sdm-ii-b-psg300-form"},
        "sdm-ii-b-psg300-form":		            {url:"$A/modules/psg300-form.html",Table:"sdm-ii-b-psg300"},
        "sdm-ii-b-fina1-data":		            {url:"$A/modules/finapres-data.html",Table:"sdm-ii-b-fina1",form_module:"sdm-ii-b-fina1-form"},
        "sdm-ii-b-fina1-form":		            {url:"$A/modules/finapres-form.html",Table:"sdm-ii-b-fina1"},
        "sdm-ii-b-fina2-data":		            {url:"$A/modules/finapres-data.html",Table:"sdm-ii-b-fina2",form_module:"sdm-ii-b-fina2-form"},
        "sdm-ii-b-fina2-form":		            {url:"$A/modules/finapres-form.html",Table:"sdm-ii-b-fina2"},
        "sdm-ii-b-fina3-data":		            {url:"$A/modules/finapres-data.html",Table:"sdm-ii-b-fina3",form_module:"sdm-ii-b-fina3-form"},
        "sdm-ii-b-fina3-form":		            {url:"$A/modules/finapres-form.html",Table:"sdm-ii-b-fina3"},
        "sdm-ii-b-nirs1-data":		            {url:"$A/modules/nirs-data.html",Table:"sdm-ii-b-nirs1",form_module:"sdm-ii-b-nirs1-form"},
        "sdm-ii-b-nirs1-form":		            {url:"$A/modules/nirs-form.html",Table:"sdm-ii-b-nirs1"},
        "sdm-ii-b-nirs2-data":		            {url:"$A/modules/nirs-data.html",Table:"sdm-ii-b-nirs2",form_module:"sdm-ii-b-nirs2-form"},
        "sdm-ii-b-nirs2-form":		            {url:"$A/modules/nirs-form.html",Table:"sdm-ii-b-nirs2"},
        "sdm-ii-b-nirs3-data":		            {url:"$A/modules/nirs-data.html",Table:"sdm-ii-b-nirs3",form_module:"sdm-ii-b-nirs3-form"},
        "sdm-ii-b-nirs3-form":		            {url:"$A/modules/nirs-form.html",Table:"sdm-ii-b-nirs3"},
        "sdm-ii-b-vr1-data":		            {url:"$A/modules/vr-data.html",Table:"sdm-ii-b-vr1",form_module:"sdm-ii-b-vr1-form"},
        "sdm-ii-b-vr1-form":		            {url:"$A/modules/vr-form.html",Table:"sdm-ii-b-vr1"},
        "sdm-ii-b-vr2-data":		            {url:"$A/modules/vr-data.html",Table:"sdm-ii-b-vr2",form_module:"sdm-ii-b-vr2-form"},
        "sdm-ii-b-vr2-form":		            {url:"$A/modules/vr-form.html",Table:"sdm-ii-b-vr2"},
        "sdm-ii-b-vr3-data":		            {url:"$A/modules/vr-data.html",Table:"sdm-ii-b-vr3",form_module:"sdm-ii-b-vr3-form"},
        "sdm-ii-b-vr3-form":		            {url:"$A/modules/vr-form.html",Table:"sdm-ii-b-vr3"},

        "sdm-ii-b-post-kss-data":		            {url:"$A/modules/kss-data.html",Table:"sdm-ii-b-post-kss",form_module:"sdm-ii-b-post-kss-form"},
        "sdm-ii-b-post-kss-form":		            {url:"$A/modules/kss-form.html",Table:"sdm-ii-b-post-kss"},
        "sdm-ii-b-post-pvt-data":		            {url:"$A/modules/pvt-data.html",Table:"sdm-ii-b-post-pvt",form_module:"sdm-ii-b-post-pvt-form"},
        "sdm-ii-b-post-pvt-form":		            {url:"$A/modules/pvt-form.html",Table:"sdm-ii-b-pre-pvt"},
        "sdm-ii-b-post-nback1-data":		        {url:"$A/modules/neurocog/nback1-data.html",Table:"sdm-ii-b-post-nback1",form_module:"sdm-ii-b-post-nback1-form"},
        "sdm-ii-b-post-nback1-form":		        {url:"$A/modules/neurocog/nback1-form.html",Table:"sdm-ii-b-post-nback1"},
        "sdm-ii-b-post-nback2-data":		        {url:"$A/modules/neurocog/nback2-data.html",Table:"sdm-ii-b-post-nback2",form_module:"sdm-ii-b-post-nback2-form"},
        "sdm-ii-b-post-nback2-form":		        {url:"$A/modules/neurocog/nback2-form.html",Table:"sdm-ii-b-post-nback2"},
        "sdm-ii-b-post-stroop-text-data":		    {url:"$A/modules/neurocog/stroop-text-data.html",Table:"sdm-ii-b-post-stroop-text",form_module:"sdm-ii-b-post-stroop-text-form"},
        "sdm-ii-b-post-stroop-text-form":		    {url:"$A/modules/neurocog/stroop-text-form.html",Table:"sdm-ii-b-post-stroop-text"},
        "sdm-ii-b-post-stroop-colour-data":		{url:"$A/modules/neurocog/stroop-colour-data.html",Table:"sdm-ii-b-post-stroop-colour",form_module:"sdm-ii-b-post-stroop-colour-form"},
        "sdm-ii-b-post-stroop-colour-form":		{url:"$A/modules/neurocog/stroop-colour-form.html",Table:"sdm-ii-b-post-stroop-colour"},
        "sdm-ii-b-post-lct-data":		            {url:"$A/modules/neurocog/lct-data.html",Table:"sdm-ii-b-post-lct",form_module:"sdm-ii-b-post-lct-form"},
        "sdm-ii-b-post-lct-form":		            {url:"$A/modules/neurocog/lct-form.html",Table:"sdm-ii-b-post-lct"},
        "sdm-ii-b-post-word-pairs-set1-morning":	    {url:"$A/modules/word-pairs/set1-morning.html"},
        "sdm-ii-b-post-word-pairs-set2-morning":	    {url:"$A/modules/word-pairs/set2-morning.html"},
        "sdm-ii-b-post-declarative-memory-test-data":		            {url:"$A/modules/declarative-memory-test-data.html",Table:"sdm-ii-b-post-declarative-memory-test",form_module:"sdm-ii-b-post-declarative-memory-test-form"},
        "sdm-ii-b-post-declarative-memory-test-form":		            {url:"$A/modules/declarative-memory-test-form.html",Table:"sdm-ii-b-post-declarative-memory-test"},
        "sdm-ii-b-post-procedural-memory-test-data":		            {url:"$A/modules/procedural-memory-test-data.html",Table:"sdm-ii-b-post-procedural-memory-test",form_module:"sdm-ii-b-post-procedural-memory-test-form"},
        "sdm-ii-b-post-procedural-memory-test-form":		            {url:"$A/modules/procedural-memory-test-form.html",Table:"sdm-ii-b-pre-procedural-memory-test"},
        "sdm-ii-b-post-ess-data":		            {url:"$A/modules/ess-data.html",Table:"sdm-ii-b-post-ess",form_module:"sdm-ii-b-post-ess-form"},
        "sdm-ii-b-post-ess-form":		            {url:"$A/modules/ess-form.html",Table:"sdm-ii-b-post-ess"},
        "sdm-ii-b-post-isi-data":		            {url:"$A/modules/isi-data.html",Table:"sdm-ii-b-post-isi",form_module:"sdm-ii-b-post-isi-form"},
        "sdm-ii-b-post-isi-form":		            {url:"$A/modules/isi-form.html",Table:"sdm-ii-b-post-isi"},
        "sdm-ii-b-post-psqi-data":		            {url:"$A/modules/psqi-data.html",Table:"sdm-ii-b-post-psqi",form_module:"sdm-ii-b-post-psqi-form"},
        "sdm-ii-b-post-psqi-form":		            {url:"$A/modules/psqi-form.html",Table:"sdm-ii-b-post-psqi"},
        "sdm-ii-b-post-hads-data":		            {url:"$A/modules/hads-data.html",Table:"sdm-ii-b-post-hads",form_module:"sdm-ii-b-post-hads-form"},
        "sdm-ii-b-post-hads-form":		            {url:"$A/modules/hads-form.html",Table:"sdm-ii-b-post-hads"},
        "sdm-ii-b-post-aused-data":		            {url:"$A/modules/aused-data.html",Table:"sdm-ii-b-post-aused",form_module:"sdm-ii-b-post-aused-form"},
        "sdm-ii-b-post-aused-form":		            {url:"$A/modules/aused-form.html",Table:"sdm-ii-b-post-aused"},

        "sdm-ii-3m-pre-pvt-data":		            {url:"$A/modules/pvt-data.html",Table:"sdm-ii-3m-pre-pvt",form_module:"sdm-ii-3m-pre-pvt-form"},
        "sdm-ii-3m-pre-pvt-form":		            {url:"$A/modules/pvt-form.html",Table:"sdm-ii-3m-pre-pvt"},
        "sdm-ii-3m-pre-word-pairs-set1-evening":	    {url:"$A/modules/word-pairs/set1-evening.html"},
        "sdm-ii-3m-pre-word-pairs-set2-evening":	    {url:"$A/modules/word-pairs/set2-evening.html"},
        "sdm-ii-3m-pre-declarative-memory-test-data":		            {url:"$A/modules/declarative-memory-test-data.html",Table:"sdm-ii-3m-pre-declarative-memory-test",form_module:"sdm-ii-3m-pre-declarative-memory-test-form"},
        "sdm-ii-3m-pre-declarative-memory-test-form":		            {url:"$A/modules/declarative-memory-test-form.html",Table:"sdm-ii-3m-pre-declarative-memory-test"},
        "sdm-ii-3m-pre-procedural-memory-test-data":		            {url:"$A/modules/procedural-memory-test-data.html",Table:"sdm-ii-3m-pre-procedural-memory-test",form_module:"sdm-ii-3m-pre-procedural-memory-test-form"},
        "sdm-ii-3m-pre-procedural-memory-test-form":		            {url:"$A/modules/procedural-memory-test-form.html",Table:"sdm-ii-3m-pre-procedural-memory-test"},
        "sdm-ii-3m-pre-kss-data":		            {url:"$A/modules/kss-data.html",Table:"sdm-ii-3m-pre-kss",form_module:"sdm-ii-3m-pre-kss-form"},
        "sdm-ii-3m-pre-kss-form":		            {url:"$A/modules/kss-form.html",Table:"sdm-ii-3m-pre-kss"},

        "sdm-ii-3m-pwa-data":		            {url:"$A/modules/pwa-data.html",Table:"sdm-ii-3m-pwa",form_module:"sdm-ii-3m-pwa-form"},
        "sdm-ii-3m-pwa-form":		            {url:"$A/modules/pwa-form.html",Table:"sdm-ii-3m-pwa"},
        "sdm-ii-3m-psg300-data":		            {url:"$A/modules/psg300-data.html",Table:"sdm-ii-3m-psg300",form_module:"sdm-ii-3m-psg300-form"},
        "sdm-ii-3m-psg300-form":		            {url:"$A/modules/psg300-form.html",Table:"sdm-ii-3m-psg300"},
        "sdm-ii-3m-fina1-data":		            {url:"$A/modules/finapres-data.html",Table:"sdm-ii-3m-fina1",form_module:"sdm-ii-3m-fina1-form"},
        "sdm-ii-3m-fina1-form":		            {url:"$A/modules/finapres-form.html",Table:"sdm-ii-3m-fina1"},
        "sdm-ii-3m-fina2-data":		            {url:"$A/modules/finapres-data.html",Table:"sdm-ii-3m-fina2",form_module:"sdm-ii-3m-fina2-form"},
        "sdm-ii-3m-fina2-form":		            {url:"$A/modules/finapres-form.html",Table:"sdm-ii-3m-fina2"},
        "sdm-ii-3m-fina3-data":		            {url:"$A/modules/finapres-data.html",Table:"sdm-ii-3m-fina3",form_module:"sdm-ii-3m-fina3-form"},
        "sdm-ii-3m-fina3-form":		            {url:"$A/modules/finapres-form.html",Table:"sdm-ii-3m-fina3"},
        "sdm-ii-3m-nirs1-data":		            {url:"$A/modules/nirs-data.html",Table:"sdm-ii-3m-nirs1",form_module:"sdm-ii-3m-nirs1-form"},
        "sdm-ii-3m-nirs1-form":		            {url:"$A/modules/nirs-form.html",Table:"sdm-ii-3m-nirs1"},
        "sdm-ii-3m-nirs2-data":		            {url:"$A/modules/nirs-data.html",Table:"sdm-ii-3m-nirs2",form_module:"sdm-ii-3m-nirs2-form"},
        "sdm-ii-3m-nirs2-form":		            {url:"$A/modules/nirs-form.html",Table:"sdm-ii-3m-nirs2"},
        "sdm-ii-3m-nirs3-data":		            {url:"$A/modules/nirs-data.html",Table:"sdm-ii-3m-nirs3",form_module:"sdm-ii-3m-nirs3-form"},
        "sdm-ii-3m-nirs3-form":		            {url:"$A/modules/nirs-form.html",Table:"sdm-ii-3m-nirs3"},
        "sdm-ii-3m-vr1-data":		            {url:"$A/modules/vr-data.html",Table:"sdm-ii-3m-vr1",form_module:"sdm-ii-3m-vr1-form"},
        "sdm-ii-3m-vr1-form":		            {url:"$A/modules/vr-form.html",Table:"sdm-ii-3m-vr1"},
        "sdm-ii-3m-vr2-data":		            {url:"$A/modules/vr-data.html",Table:"sdm-ii-3m-vr2",form_module:"sdm-ii-3m-vr2-form"},
        "sdm-ii-3m-vr2-form":		            {url:"$A/modules/vr-form.html",Table:"sdm-ii-3m-vr2"},
        "sdm-ii-3m-vr3-data":		            {url:"$A/modules/vr-data.html",Table:"sdm-ii-3m-vr3",form_module:"sdm-ii-3m-vr3-form"},
        "sdm-ii-3m-vr3-form":		            {url:"$A/modules/vr-form.html",Table:"sdm-ii-3m-vr3"},

        "sdm-ii-3m-post-kss-data":		            {url:"$A/modules/kss-data.html",Table:"sdm-ii-3m-post-kss",form_module:"sdm-ii-3m-post-kss-form"},
        "sdm-ii-3m-post-kss-form":		            {url:"$A/modules/kss-form.html",Table:"sdm-ii-3m-post-kss"},
        "sdm-ii-3m-post-pvt-data":		            {url:"$A/modules/pvt-data.html",Table:"sdm-ii-3m-post-pvt",form_module:"sdm-ii-3m-post-pvt-form"},
        "sdm-ii-3m-post-pvt-form":		            {url:"$A/modules/pvt-form.html",Table:"sdm-ii-3m-pre-pvt"},
        "sdm-ii-3m-post-nback1-data":		        {url:"$A/modules/neurocog/nback1-data.html",Table:"sdm-ii-3m-post-nback1",form_module:"sdm-ii-3m-post-nback1-form"},
        "sdm-ii-3m-post-nback1-form":		        {url:"$A/modules/neurocog/nback1-form.html",Table:"sdm-ii-3m-post-nback1"},
        "sdm-ii-3m-post-nback2-data":		        {url:"$A/modules/neurocog/nback2-data.html",Table:"sdm-ii-3m-post-nback2",form_module:"sdm-ii-3m-post-nback2-form"},
        "sdm-ii-3m-post-nback2-form":		        {url:"$A/modules/neurocog/nback2-form.html",Table:"sdm-ii-3m-post-nback2"},
        "sdm-ii-3m-post-stroop-text-data":		    {url:"$A/modules/neurocog/stroop-text-data.html",Table:"sdm-ii-3m-post-stroop-text",form_module:"sdm-ii-3m-post-stroop-text-form"},
        "sdm-ii-3m-post-stroop-text-form":		    {url:"$A/modules/neurocog/stroop-text-form.html",Table:"sdm-ii-3m-post-stroop-text"},
        "sdm-ii-3m-post-stroop-colour-data":		{url:"$A/modules/neurocog/stroop-colour-data.html",Table:"sdm-ii-3m-post-stroop-colour",form_module:"sdm-ii-3m-post-stroop-colour-form"},
        "sdm-ii-3m-post-stroop-colour-form":		{url:"$A/modules/neurocog/stroop-colour-form.html",Table:"sdm-ii-3m-post-stroop-colour"},
        "sdm-ii-3m-post-lct-data":		            {url:"$A/modules/neurocog/lct-data.html",Table:"sdm-ii-3m-post-lct",form_module:"sdm-ii-3m-post-lct-form"},
        "sdm-ii-3m-post-lct-form":		            {url:"$A/modules/neurocog/lct-form.html",Table:"sdm-ii-3m-post-lct"},
        "sdm-ii-3m-post-word-pairs-set1-morning":	    {url:"$A/modules/word-pairs/set1-morning.html"},
        "sdm-ii-3m-post-word-pairs-set2-morning":	    {url:"$A/modules/word-pairs/set2-morning.html"},
        "sdm-ii-3m-post-declarative-memory-test-data":		            {url:"$A/modules/declarative-memory-test-data.html",Table:"sdm-ii-3m-post-declarative-memory-test",form_module:"sdm-ii-3m-post-declarative-memory-test-form"},
        "sdm-ii-3m-post-declarative-memory-test-form":		            {url:"$A/modules/declarative-memory-test-form.html",Table:"sdm-ii-3m-post-declarative-memory-test"},
        "sdm-ii-3m-post-procedural-memory-test-data":		            {url:"$A/modules/procedural-memory-test-data.html",Table:"sdm-ii-3m-post-procedural-memory-test",form_module:"sdm-ii-3m-post-procedural-memory-test-form"},
        "sdm-ii-3m-post-procedural-memory-test-form":		            {url:"$A/modules/procedural-memory-test-form.html",Table:"sdm-ii-3m-pre-procedural-memory-test"},
        "sdm-ii-3m-post-ess-data":		            {url:"$A/modules/ess-data.html",Table:"sdm-ii-3m-post-ess",form_module:"sdm-ii-3m-post-ess-form"},
        "sdm-ii-3m-post-ess-form":		            {url:"$A/modules/ess-form.html",Table:"sdm-ii-3m-post-ess"},
        "sdm-ii-3m-post-isi-data":		            {url:"$A/modules/isi-data.html",Table:"sdm-ii-3m-post-isi",form_module:"sdm-ii-3m-post-isi-form"},
        "sdm-ii-3m-post-isi-form":		            {url:"$A/modules/isi-form.html",Table:"sdm-ii-3m-post-isi"},
        "sdm-ii-3m-post-psqi-data":		            {url:"$A/modules/psqi-data.html",Table:"sdm-ii-3m-post-psqi",form_module:"sdm-ii-3m-post-psqi-form"},
        "sdm-ii-3m-post-psqi-form":		            {url:"$A/modules/psqi-form.html",Table:"sdm-ii-3m-post-psqi"},
        "sdm-ii-3m-post-hads-data":		            {url:"$A/modules/hads-data.html",Table:"sdm-ii-3m-post-hads",form_module:"sdm-ii-3m-post-hads-form"},
        "sdm-ii-3m-post-hads-form":		            {url:"$A/modules/hads-form.html",Table:"sdm-ii-3m-post-hads"},
        "sdm-ii-3m-post-aused-data":		            {url:"$A/modules/aused-data.html",Table:"sdm-ii-3m-post-aused",form_module:"sdm-ii-3m-post-aused-form"},
        "sdm-ii-3m-post-aused-form":		            {url:"$A/modules/aused-form.html",Table:"sdm-ii-3m-post-aused"},
   }
    for(m in modules){$vm.module_list[m]=modules[m];}
})();
